export const permits = [
  {
    permitNumber: "PBAR34243234234",
    permitType: "Barricade",
    projectName: "Road work",
    location: "Some Location",
    status: "Active",
    applicantName: "John Smith",
    applicantCompany: "ABC Company",
    applicantAddress: "123 some street",
    district: "TBA",
    primeContractorName: "Ed Smith",
    primeContractorCompany: "ABC Company",
    primeContractorAddress: "123 some street",
    barricadeContractorName: "John Smith",
    barricadeContractorCompany: "ABC Company",
    barricadeContractorAddress: "123 some street",
    responsibleParty: "TBA",
    issuedDate: "07/15/2021",
    plannedStartTime: "TBA",
    actualStartTime: "TBA",
    plannedEndTime: "TBA",
    actualEndTime: "TBA",
    appliedDate: "07/01/2021",
    finalizedDate: "TBA",
    expirationDate: "TBA",
    trafficSignal: "No",
  },
  {
    permitNumber: "PBAR34776555",
    permitType: "Barricade",
    projectName: "Road work",
    location: "Some Location",
    status: "Active",
    applicantName: "John Smith",
    applicantCompany: "ABC Company",
    applicantAddress: "123 some street",
    district: "TBA",
    primeContractorName: "Ed Smith",
    primeContractorCompany: "ABC Company",
    primeContractorAddress: "123 some street",
    barricadeContractorName: "John Smith",
    barricadeContractorCompany: "ABC Company",
    barricadeContractorAddress: "123 some street",
    responsibleParty: "TBA",
    issuedDate: "07/15/2021",
    plannedStartTime: "TBA",
    actualStartTime: "TBA",
    plannedEndTime: "TBA",
    actualEndTime: "TBA",
    appliedDate: "07/01/2021",
    finalizedDate: "TBA",
    expirationDate: "TBA",
    trafficSignal: "No",
  },
  {
    permitNumber: "PBAR34223145235",
    permitType: "Barricade",
    projectName: "Road work",
    location: "Some Location",
    status: "Active",
    applicantName: "John Smith",
    applicantCompany: "ABC Company",
    applicantAddress: "123 some street",
    district: "TBA",
    primeContractorName: "Ed Smith",
    primeContractorCompany: "ABC Company",
    primeContractorAddress: "123 some street",
    barricadeContractorName: "John Smith",
    barricadeContractorCompany: "ABC Company",
    barricadeContractorAddress: "123 some street",
    responsibleParty: "TBA",
    issuedDate: "07/15/2021",
    plannedStartTime: "TBA",
    actualStartTime: "TBA",
    plannedEndTime: "TBA",
    actualEndTime: "TBA",
    appliedDate: "07/01/2021",
    expirationDate: "TBA",
    finalizedDate: "TBA",
    trafficSignal: "No",
  },
];

export const lineItemKeys = {
  permitType: "Permit Type",
  projectName: "Project Name",
  location: "Location",
  status: "Status",
  district: "District",
  applicantName: "Applicant Name",
  applicantCompany: "Applicant Company",
  applicantAddress: "Applicant Address",
  primeContractorName: "Prime Contractor",
  primeContractorCompany: "Prime Contractor Company",
  primeContractorAddress: "Prime Contractor Address",
  barricadeContractorName: "Barricade Contractor",
  barricadeContractorCompany: "Barricade Contractor Company",
  barricadeContractorAddress: "Barricade Contractor Address",
  responsibleParty: "Responsible Party",
  issuedDate: "Issued Date",
  plannedStartTime: "Planned Start Time",
  actualStartTime: "Actual Start Time",
  plannedEndTime: "Planned End Time",
  actualEndTime: "Actual End Time",
  appliedDate: "Applied Date",
  expirationDate: "Expiration Date",
  finalizedDate: "Finalized Date",
  trafficSignal: "Within 300' of Traffic Signal",
};
